#!/bin/tcsh -f

# CMSC 216, spring 2022, run_is_palindrome.s

cat is_palindrome_driver.s is_palindrome.s > is_palindrome_prog.s
spim -file is_palindrome_prog.s | tail -n +2
rm -f is_palindrome_prog.s
# "tail -n+2" strips the first line of spim's output, which is irrelevant

cat reverse_prefix_sum_driver.s reverse_prefix_sum.s > reverse_prefix_sum_prog.s
spim -file reverse_prefix_sum_prog.s | tail -n +2
rm -f reverse_prefix_sum_prog.s

cat isqrt_driver.s isqrt.s > isqrt_prog.s
spim -file isqrt_prog.s | tail -n +2
rm -f isqrt_prog.s